version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install nasm xorriso build-essential grub2-common
      - run: make
      - run: test -f build/isofiles/boot/kernel.bin
      - run: test -f build/willOS.iso
